import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { Toaster } from 'sonner';

const ibmPlexArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex",
});

import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/header/Navbar";
import { Sidebar } from "./components/sidebar/Sidebar";
import QueryProvider from "./providers/QueryProvider";

export const metadata: Metadata = {
  title: "لوحة التحكم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={ibmPlexArabic.variable}>
      <body className="">
        <QueryProvider>
            <Navbar />
            <div className="bg-[#eee] main-container py-6 px-0! sm:px-4! flex gap-5 h-[calc(100vh-72px)] ">
                <Sidebar />
                <div className="bg-glass-bg bg-white backdrop-blur-(--sidebar-blur) rounded-3xl shadow-lg w-full h-full p-4 overflow-y-auto custom-scrollbar" >
                    {children}
                </div>
            </div>
        </QueryProvider>
        <Toaster position="top-center" dir="rtl" richColors closeButton />
      </body>
    </html>
  );
}
